version: '3.9'

services:

  backtest-quotation:
    image: imwhiteflag/quotation:1.0.0
    mem_limit: 128m
    environment:
      - BACKTEST_DB_USERNAME=postgres
      - BACKTEST_DB_PASSWORD=postgres
      - BACKTEST_DB_URI=jdbc:postgresql://postgres:5432/quotation
      - BACKTEST_JAEGER_URI=http://jaeger:14268/api/traces
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service

  backtest-app:
    image: imwhiteflag/quotation-app:0.1.0
    mem_limit: 256m
    ports:
      - "80:80"
    depends_on:
      - backtest-quotation
    networks:
      - service
    
  postgres:
    image: postgres
    mem_limit: 128m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotation
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 5s
      timeout: 5s
      retries: 6
    networks:
      - service
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.36.2
    mem_limit: 256m
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - service
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    mem_limit: 128m
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/quotation?sslmode=disable"
    depends_on:
      - prometheus
      - postgres
    networks:
      - service
      
  grafana:
    image: grafana/grafana
    mem_limit: 256m
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - service
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    mem_limit: 256m
    ports:
      - "6831:6831/udp"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    networks:
      - service

networks:
  service:
    driver: bridge

volumes:
  postgres:
  grafana_data:
  prometheus_data: